### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by nerg4l**
This is the last step to make [grumphp](https://github.com/phpro/grumphp) green.

I removed `php-vcr` and added a very simple filesystem cache. The content of the cache is version controlled because some date (last comment details, scores) can change in every second. To be able to run these tests against MAL every day/week/month we have to use less strict assertions. This change is related to #371.

### CODE REVIEW

**Comment by nerg4l** [comment]
AppVeyor still fails. Unfortunately, I'm not familiar with that.

**Comment by pushrbx** [comment]
AppVeyor config is out of date, it's checking for older php versions.

**Comment by irfan-dahir** [comment]
> AppVeyor config is out of date, it's checking for older php versions.
Also do we want to test things on windows? I think I can write a github actions equivalent.

We can drop AppVeyor, it was mainly added for testing on windows but we dropped windows support quite a while back.

**Comment by irfan-dahir** [comment]
The HTTP cache is also being pushed to the repo as well. Would it be possible to push them to the fixtures repo instead?
https://github.com/jikan-me/jikan-fixtures
It would require changing cache read/write to `vendor/jikan-me/jikan-fixtures/fixtures`

We can link them with `composer run-script link-fixtures`:
https://github.com/jikan-me/jikan/blob/de68f87c64b11910fc70aed26e3a92f22f1af9b9/composer.json#L44

**Comment by nerg4l** [comment]
@irfan-dahir Could you apply the necessary changes? I'm not sure what I have to do. You can control the path in `JikanTest\TestCase`.

**Comment by irfan-dahir** [comment]
[Created PR](https://github.com/nerg4l/jikan/pull/1) (needs to be merged before it shows up here) which moves http cache to [jikan-fixtures](https://github.com/jikan-me/jikan-fixtures).

If any new tests are being added, it's recommended to link the fixtures so any changes would be made as commits to [jikan-fixtures](https://github.com/jikan-me/jikan-fixtures).

You can link the fixtures by running the composer script `link-fixtures`.

**Comment by irfan-dahir** [comment]
HTTP Cache has been moved to [jikan-fixtures](https://github.com/jikan-me/jikan-fixtures).

If any new tests are being added, it's recommended to link the fixtures so any changes would be made as commits to [jikan-fixtures](https://github.com/jikan-me/jikan-fixtures).

You can link the fixtures by running the composer script `composer link-fixtures`. Invited you both for write access on the `jikan-fixtures` repo as well.

**Pull request merged**
