### PR TITLE
Code style updates + tests

### PR DESCRIPTION
**Pull request by janvernieuwe**

### CODE REVIEW

**Comment by janvernieuwe** [comment]
@irfan-dahir Can you resolve these?
They happened while you were working on it i guess.

**Comment by irfan-dahir** [comment]
Thanks, sure thing. 

I've uploaded an example on the request (https://github.com/jikan-me/jikan/blob/2.0.0-dev/test/test.php).

**Request** classes are the appropriate request, e.g Main page, Episodes page, characters, etc.
**Helper** classes are if there's more arguments to be set. E.g in advanced search or on the episodes page where there's pagination.

I'll add a legacy support for requests based on the new way.

**Comment by janvernieuwe** [comment]
nm, i accepted your changes.
Need to get the tests working first

**Comment by irfan-dahir** [comment]
@janvernieuwe I'll go ahead and merge it, we can work the master branch?

Btw, `Get.Old` & `Lib.Old` are depreciated in 2.0, they're there for reference. The new directories are `Get` (same name) and `Parser` respectively.

**Comment by janvernieuwe** [comment]
Are you on a chat somewhere perhaps, probably easier then this the whole time

**Comment by irfan-dahir** [comment]
Indeed :d `Nekomata#0428`

**Comment by janvernieuwe** [comment]
No common servers it seems, maybe a good idea to create one for the project?

**Comment by irfan-dahir** [comment]
Sure, give me a min.

**Comment by irfan-dahir** [comment]
@janvernieuwe https://discord.gg/UjgneP

**Pull request merged**
