### PR TITLE
Codestyle

### PR DESCRIPTION
**Pull request by janvernieuwe**
Try to move towards PSR2 compatibility, at least a little, so that code can be auto formatted correctly.
These are mainly fixes and improvements done with tools.

If this is merged, I'll try to improve whatever I touch when i add new things.

(merge 156 first)

### CODE REVIEW

**Comment by irfan-dahir** [comment]
Awesome! Thank you!

Quick thing regarding Profile Parsing, I'm working on Jikan 2.0.0 (https://github.com/jikan-me/jikan/tree/2.0.0-dev) which uses a custom scraping dependency I've made (https://github.com/irfan-dahir/skraypar) which uses Guzzle and is a complete refactor of the code.

Please create the Profile parser there. :)

P.S MAL has currently set profile views to private, which means you can only view your own profile given you're logged in.

**Comment by janvernieuwe** [comment]
Do you want me to give that branch the works too?

**Comment by irfan-dahir** [comment]
Gotcha, thank you :)

**Comment by irfan-dahir** [comment]
Update: It seems MAL has enabled profile viewing for other and unauthenticated users.

**Pull request merged**
