### PR TITLE
Update Goutte to version 4 removing the GuzzlePHP dependency

### PR DESCRIPTION
**Pull request by rjd22**
The PHPUnit tests seem to not work anymore so I didn't update them but I did an integration test on my own any it seems to work correctly. I'm just making this PR to share my change.

This is a breaking change I would say so you might want me to target it to the 3.0 branch.

### CODE REVIEW

**Comment by irfan-dahir** [comment]
Thanks for the PR! If you could target the 3.0 branch that would be great and I can go ahead and review it for merging. I believe it should also resolve https://github.com/jikan-me/jikan/issues/323

**Comment by rjd22** [comment]
@irfan-dahir I rebased it to 3.0.0. I'm also running this on PHP version 8.0 and it's running fine. Do you want me to make a separate PR that enables PHP 8.0 for this package?

**Comment by irfan-dahir** [comment]
Thanks @rjd22 , I'll test this out and let you know!

As for 8.0, let's put it on hold for a bit. I need to make sure the tests and Lumen framework both support it.

**Comment by janvernieuwe** [comment]
Perhaps add suggests for symfony http client and guzzle.
Documentation also needs to be updated that the correct adapters need to be required.

**Comment by rjd22** [comment]
@janvernieuwe sadly the Guzzle version is incompatible with the SymfonyHttpClient version. The upgrade is one way. I think dropping guzzle completely for this library on a major version is reasonable.

**Comment by rjd22** [comment]
@irfan-dahir would it be possible to get this one merged? The old Guzzle version would be really blocking for using the new 3.0 release.

**Comment by irfan-dahir** [comment]
@rjd22 For sure - I will review and merge it before the end of the week.

**Comment by rjd22** [comment]
Thank you @irfan-dahir !

**Pull request merged**
